TARGET  := tdsungard_svr

LIBS    +=  -Wl,-Bstatic -L../base/ -lfuture -lctp -lsungard -lcommon -lencrypt  ${LIB_SUNGARD}

INCLUDE += -I./  -I../base/ 

include ../../Makefile

include ../Makefile.inc

