TARGET  := tdsungard_svr

LIBS    +=  -Wl,-Bstatic -L../base/ -lfuture -lctp -lsungard -lcommon -lencrypt  ${LIB_SUNGARD}

INCLUDE += -I./  -I../base/ -D  __SUNGARD__VERSION__=16 

include ../../Makefile

include ../Makefile.inc

