TARGET  := tdsungard_svr

LIBS    +=  -Wl,-Bstatic -L../base/ -lfuture -lctp -lsungard.1.6 -lcommon -lencrypt  ${LIB_SUNGARD16}

INCLUDE += -I./  -I../base/ -D  __SUNGARD__VERSION__=16

include ../../Makefile

include ../Makefile.inc

