TARGET  := tdctp_svr

LIBS    +=  -Wl,-Bstatic -L../base/ -lfuture -lctp.619 -lcommon -lencrypt  ${LIB_CTP_TD_619}

INCLUDE += -I./  -I../base/ -D  __CTP__VERSION__=619

include ../../Makefile

include ../Makefile.inc

