// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `test.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __test_h__
#define __test_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Test
{

class TT;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Test::TT>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Test::TT*);

}

}

namespace Test
{

class TT;
::Ice::Object* upCast(::Test::TT*);
typedef ::IceInternal::Handle< ::Test::TT> TTPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Test::TT> TTPrx;
void __patch(TTPtr&, const ::Ice::ObjectPtr&);

}

namespace Test
{

struct T
{
    ::Ice::Int age;
    ::std::string name;

    bool operator==(const T& __rhs) const
    {
        if(this == &__rhs)
        {
            return true;
        }
        if(age != __rhs.age)
        {
            return false;
        }
        if(name != __rhs.name)
        {
            return false;
        }
        return true;
    }

    bool operator<(const T& __rhs) const
    {
        if(this == &__rhs)
        {
            return false;
        }
        if(age < __rhs.age)
        {
            return true;
        }
        else if(__rhs.age < age)
        {
            return false;
        }
        if(name < __rhs.name)
        {
            return true;
        }
        else if(__rhs.name < name)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const T& __rhs) const
    {
        return !operator==(__rhs);
    }
    bool operator<=(const T& __rhs) const
    {
        return operator<(__rhs) || operator==(__rhs);
    }
    bool operator>(const T& __rhs) const
    {
        return !operator<(__rhs) && !operator==(__rhs);
    }
    bool operator>=(const T& __rhs) const
    {
        return !operator<(__rhs);
    }
};

struct TTT
{
    ::Test::T t;
    ::std::string msg;

    bool operator==(const TTT& __rhs) const
    {
        if(this == &__rhs)
        {
            return true;
        }
        if(t != __rhs.t)
        {
            return false;
        }
        if(msg != __rhs.msg)
        {
            return false;
        }
        return true;
    }

    bool operator<(const TTT& __rhs) const
    {
        if(this == &__rhs)
        {
            return false;
        }
        if(t < __rhs.t)
        {
            return true;
        }
        else if(__rhs.t < t)
        {
            return false;
        }
        if(msg < __rhs.msg)
        {
            return true;
        }
        else if(__rhs.msg < msg)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const TTT& __rhs) const
    {
        return !operator==(__rhs);
    }
    bool operator<=(const TTT& __rhs) const
    {
        return operator<(__rhs) || operator==(__rhs);
    }
    bool operator>(const TTT& __rhs) const
    {
        return !operator<(__rhs) && !operator==(__rhs);
    }
    bool operator>=(const TTT& __rhs) const
    {
        return !operator<(__rhs);
    }
};

typedef ::std::vector< ::Test::T> TType;

typedef ::std::map< ::std::string, ::Test::T> MapType;

}

namespace Ice
{
template<>
struct StreamableTraits< ::Test::T>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 5;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::Test::T, S>
{
    static void write(S* __os, const ::Test::T& v)
    {
        __os->write(v.age);
        __os->write(v.name);
    }
};

template<class S>
struct StreamReader< ::Test::T, S>
{
    static void read(S* __is, ::Test::T& v)
    {
        __is->read(v.age);
        __is->read(v.name);
    }
};

template<>
struct StreamableTraits< ::Test::TTT>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 6;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::Test::TTT, S>
{
    static void write(S* __os, const ::Test::TTT& v)
    {
        __os->write(v.t);
        __os->write(v.msg);
    }
};

template<class S>
struct StreamReader< ::Test::TTT, S>
{
    static void read(S* __is, ::Test::TTT& v)
    {
        __is->read(v.t);
        __is->read(v.msg);
    }
};

}

namespace Test
{

class Callback_TT_push_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_TT_push_Base> Callback_TT_pushPtr;

}

namespace IceProxy
{

namespace Test
{

class TT : virtual public ::IceProxy::Ice::Object
{
public:

    void push(const ::Test::TType& __p_t, const ::Test::MapType& __p_tt)
    {
        push(__p_t, __p_tt, 0);
    }
    void push(const ::Test::TType& __p_t, const ::Test::MapType& __p_tt, const ::Ice::Context& __ctx)
    {
        push(__p_t, __p_tt, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_push(const ::Test::TType& __p_t, const ::Test::MapType& __p_tt, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_push(__p_t, __p_tt, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_push(const ::Test::TType& __p_t, const ::Test::MapType& __p_tt, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_push(__p_t, __p_tt, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_push(const ::Test::TType& __p_t, const ::Test::MapType& __p_tt, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_push(__p_t, __p_tt, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_push(const ::Test::TType& __p_t, const ::Test::MapType& __p_tt, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_push(__p_t, __p_tt, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_push(const ::Test::TType& __p_t, const ::Test::MapType& __p_tt)
    {
        return begin_push(__p_t, __p_tt, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_push(const ::Test::TType& __p_t, const ::Test::MapType& __p_tt, const ::Ice::Context& __ctx)
    {
        return begin_push(__p_t, __p_tt, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_push(const ::Test::TType& __p_t, const ::Test::MapType& __p_tt, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_push(__p_t, __p_tt, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_push(const ::Test::TType& __p_t, const ::Test::MapType& __p_tt, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_push(__p_t, __p_tt, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_push(const ::Test::TType& __p_t, const ::Test::MapType& __p_tt, const ::Test::Callback_TT_pushPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_push(__p_t, __p_tt, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_push(const ::Test::TType& __p_t, const ::Test::MapType& __p_tt, const ::Ice::Context& __ctx, const ::Test::Callback_TT_pushPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_push(__p_t, __p_tt, &__ctx, __del, __cookie);
    }

    void end_push(const ::Ice::AsyncResultPtr&);
    
private:

    void push(const ::Test::TType&, const ::Test::MapType&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_push(const ::Test::TType&, const ::Test::MapType&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<TT> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_secure(bool __secure) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_twoway() const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_oneway() const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_batchOneway() const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_datagram() const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_batchDatagram() const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_compress(bool __compress) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_timeout(int __timeout) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<TT> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<TT*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace Test
{

class TT : virtual public ::Ice::Object
{
public:

    typedef TTPrx ProxyType;
    typedef TTPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void push(const ::Test::TType&, const ::Test::MapType&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___push(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const TT& l, const TT& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const TT& l, const TT& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Test
{

template<class T>
class CallbackNC_TT_push : public Callback_TT_push_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_TT_push(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_TT_pushPtr
newCallback_TT_push(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TT_push<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TT_pushPtr
newCallback_TT_push(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TT_push<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_TT_pushPtr
newCallback_TT_push(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TT_push<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TT_pushPtr
newCallback_TT_push(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TT_push<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_TT_push : public Callback_TT_push_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_TT_push(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_TT_pushPtr
newCallback_TT_push(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TT_push<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TT_pushPtr
newCallback_TT_push(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TT_push<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_TT_pushPtr
newCallback_TT_push(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TT_push<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TT_pushPtr
newCallback_TT_push(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TT_push<T, CT>(instance, 0, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
