// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `MdPastSession.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __MdPastSession_h__
#define __MdPastSession_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/Identity.h>
#include <ice/Common.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace MdPast
{

class MdSessionCallBack;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::MdPast::MdSessionCallBack>&);
::IceProxy::Ice::Object* upCast(::IceProxy::MdPast::MdSessionCallBack*);

class MdSession;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::MdPast::MdSession>&);
::IceProxy::Ice::Object* upCast(::IceProxy::MdPast::MdSession*);

}

}

namespace MdPast
{

class MdSessionCallBack;
::Ice::Object* upCast(::MdPast::MdSessionCallBack*);
typedef ::IceInternal::Handle< ::MdPast::MdSessionCallBack> MdSessionCallBackPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::MdPast::MdSessionCallBack> MdSessionCallBackPrx;
void __patch(MdSessionCallBackPtr&, const ::Ice::ObjectPtr&);

class MdSession;
::Ice::Object* upCast(::MdPast::MdSession*);
typedef ::IceInternal::Handle< ::MdPast::MdSession> MdSessionPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::MdPast::MdSession> MdSessionPrx;
void __patch(MdSessionPtr&, const ::Ice::ObjectPtr&);

}

namespace MdPast
{

typedef ::std::vector< ::std::string> StringList;

typedef ::std::vector< ::Ice::Int> IntList;

}

namespace MdPast
{

class Callback_MdSessionCallBack_onTick_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_MdSessionCallBack_onTick_Base> Callback_MdSessionCallBack_onTickPtr;

class Callback_MdSessionCallBack_onBar_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_MdSessionCallBack_onBar_Base> Callback_MdSessionCallBack_onBarPtr;

class Callback_MdSessionCallBack_onDay_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_MdSessionCallBack_onDay_Base> Callback_MdSessionCallBack_onDayPtr;

class Callback_MdSession_queryData_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_MdSession_queryData_Base> Callback_MdSession_queryDataPtr;

class Callback_MdSession_queryInstruments_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_MdSession_queryInstruments_Base> Callback_MdSession_queryInstrumentsPtr;

}

namespace IceProxy
{

namespace MdPast
{

class MdSessionCallBack : virtual public ::IceProxy::Ice::Object
{
public:

    ::Ice::Int onTick(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Ticker& __p_ticker)
    {
        return onTick(__p_TradingDay, __p_InstrumentID, __p_ticker, 0);
    }
    ::Ice::Int onTick(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Ticker& __p_ticker, const ::Ice::Context& __ctx)
    {
        return onTick(__p_TradingDay, __p_InstrumentID, __p_ticker, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_onTick(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Ticker& __p_ticker, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_onTick(__p_TradingDay, __p_InstrumentID, __p_ticker, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_onTick(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Ticker& __p_ticker, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_onTick(__p_TradingDay, __p_InstrumentID, __p_ticker, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_onTick(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Ticker& __p_ticker, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_onTick(__p_TradingDay, __p_InstrumentID, __p_ticker, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_onTick(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Ticker& __p_ticker, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_onTick(__p_TradingDay, __p_InstrumentID, __p_ticker, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_onTick(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Ticker& __p_ticker, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_onTick(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Ticker& __p_ticker)
    {
        return begin_onTick(__p_TradingDay, __p_InstrumentID, __p_ticker, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_onTick(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Ticker& __p_ticker, const ::Ice::Context& __ctx)
    {
        return begin_onTick(__p_TradingDay, __p_InstrumentID, __p_ticker, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_onTick(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Ticker& __p_ticker, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_onTick(__p_TradingDay, __p_InstrumentID, __p_ticker, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_onTick(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Ticker& __p_ticker, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_onTick(__p_TradingDay, __p_InstrumentID, __p_ticker, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_onTick(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Ticker& __p_ticker, const ::MdPast::Callback_MdSessionCallBack_onTickPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_onTick(__p_TradingDay, __p_InstrumentID, __p_ticker, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_onTick(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Ticker& __p_ticker, const ::Ice::Context& __ctx, const ::MdPast::Callback_MdSessionCallBack_onTickPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_onTick(__p_TradingDay, __p_InstrumentID, __p_ticker, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_onTick(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int onTick(const ::std::string&, const ::std::string&, const ::CM::Ticker&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_onTick(const ::std::string&, const ::std::string&, const ::CM::Ticker&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int onBar(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Bar& __p_bar, ::Ice::Int __p_period)
    {
        return onBar(__p_TradingDay, __p_InstrumentID, __p_bar, __p_period, 0);
    }
    ::Ice::Int onBar(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Bar& __p_bar, ::Ice::Int __p_period, const ::Ice::Context& __ctx)
    {
        return onBar(__p_TradingDay, __p_InstrumentID, __p_bar, __p_period, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_onBar(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Bar& __p_bar, ::Ice::Int __p_period, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_onBar(__p_TradingDay, __p_InstrumentID, __p_bar, __p_period, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_onBar(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Bar& __p_bar, ::Ice::Int __p_period, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_onBar(__p_TradingDay, __p_InstrumentID, __p_bar, __p_period, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_onBar(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Bar& __p_bar, ::Ice::Int __p_period, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_onBar(__p_TradingDay, __p_InstrumentID, __p_bar, __p_period, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_onBar(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Bar& __p_bar, ::Ice::Int __p_period, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_onBar(__p_TradingDay, __p_InstrumentID, __p_bar, __p_period, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_onBar(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Bar& __p_bar, ::Ice::Int __p_period, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_onBar(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Bar& __p_bar, ::Ice::Int __p_period)
    {
        return begin_onBar(__p_TradingDay, __p_InstrumentID, __p_bar, __p_period, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_onBar(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Bar& __p_bar, ::Ice::Int __p_period, const ::Ice::Context& __ctx)
    {
        return begin_onBar(__p_TradingDay, __p_InstrumentID, __p_bar, __p_period, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_onBar(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Bar& __p_bar, ::Ice::Int __p_period, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_onBar(__p_TradingDay, __p_InstrumentID, __p_bar, __p_period, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_onBar(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Bar& __p_bar, ::Ice::Int __p_period, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_onBar(__p_TradingDay, __p_InstrumentID, __p_bar, __p_period, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_onBar(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Bar& __p_bar, ::Ice::Int __p_period, const ::MdPast::Callback_MdSessionCallBack_onBarPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_onBar(__p_TradingDay, __p_InstrumentID, __p_bar, __p_period, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_onBar(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::Bar& __p_bar, ::Ice::Int __p_period, const ::Ice::Context& __ctx, const ::MdPast::Callback_MdSessionCallBack_onBarPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_onBar(__p_TradingDay, __p_InstrumentID, __p_bar, __p_period, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_onBar(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int onBar(const ::std::string&, const ::std::string&, const ::CM::Bar&, ::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_onBar(const ::std::string&, const ::std::string&, const ::CM::Bar&, ::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int onDay(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::DayBar& __p_day)
    {
        return onDay(__p_TradingDay, __p_InstrumentID, __p_day, 0);
    }
    ::Ice::Int onDay(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::DayBar& __p_day, const ::Ice::Context& __ctx)
    {
        return onDay(__p_TradingDay, __p_InstrumentID, __p_day, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_onDay(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::DayBar& __p_day, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_onDay(__p_TradingDay, __p_InstrumentID, __p_day, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_onDay(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::DayBar& __p_day, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_onDay(__p_TradingDay, __p_InstrumentID, __p_day, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_onDay(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::DayBar& __p_day, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_onDay(__p_TradingDay, __p_InstrumentID, __p_day, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_onDay(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::DayBar& __p_day, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_onDay(__p_TradingDay, __p_InstrumentID, __p_day, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_onDay(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::DayBar& __p_day, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_onDay(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::DayBar& __p_day)
    {
        return begin_onDay(__p_TradingDay, __p_InstrumentID, __p_day, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_onDay(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::DayBar& __p_day, const ::Ice::Context& __ctx)
    {
        return begin_onDay(__p_TradingDay, __p_InstrumentID, __p_day, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_onDay(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::DayBar& __p_day, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_onDay(__p_TradingDay, __p_InstrumentID, __p_day, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_onDay(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::DayBar& __p_day, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_onDay(__p_TradingDay, __p_InstrumentID, __p_day, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_onDay(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::DayBar& __p_day, const ::MdPast::Callback_MdSessionCallBack_onDayPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_onDay(__p_TradingDay, __p_InstrumentID, __p_day, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_onDay(const ::std::string& __p_TradingDay, const ::std::string& __p_InstrumentID, const ::CM::DayBar& __p_day, const ::Ice::Context& __ctx, const ::MdPast::Callback_MdSessionCallBack_onDayPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_onDay(__p_TradingDay, __p_InstrumentID, __p_day, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_onDay(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int onDay(const ::std::string&, const ::std::string&, const ::CM::DayBar&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_onDay(const ::std::string&, const ::std::string&, const ::CM::DayBar&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_secure(bool __secure) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_twoway() const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_oneway() const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_batchOneway() const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_datagram() const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_batchDatagram() const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_compress(bool __compress) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_timeout(int __timeout) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<MdSessionCallBack> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<MdSessionCallBack*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

class MdSession : virtual public ::IceProxy::Ice::Object
{
public:

    ::std::string queryData(const ::Ice::Identity& __p_ident, const ::std::string& __p_DataType, const ::std::string& __p_InstrumentID, const ::std::string& __p_starttime, const ::std::string& __p_endtime)
    {
        return queryData(__p_ident, __p_DataType, __p_InstrumentID, __p_starttime, __p_endtime, 0);
    }
    ::std::string queryData(const ::Ice::Identity& __p_ident, const ::std::string& __p_DataType, const ::std::string& __p_InstrumentID, const ::std::string& __p_starttime, const ::std::string& __p_endtime, const ::Ice::Context& __ctx)
    {
        return queryData(__p_ident, __p_DataType, __p_InstrumentID, __p_starttime, __p_endtime, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_queryData(const ::Ice::Identity& __p_ident, const ::std::string& __p_DataType, const ::std::string& __p_InstrumentID, const ::std::string& __p_starttime, const ::std::string& __p_endtime, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_queryData(__p_ident, __p_DataType, __p_InstrumentID, __p_starttime, __p_endtime, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_queryData(const ::Ice::Identity& __p_ident, const ::std::string& __p_DataType, const ::std::string& __p_InstrumentID, const ::std::string& __p_starttime, const ::std::string& __p_endtime, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_queryData(__p_ident, __p_DataType, __p_InstrumentID, __p_starttime, __p_endtime, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_queryData(const ::Ice::Identity& __p_ident, const ::std::string& __p_DataType, const ::std::string& __p_InstrumentID, const ::std::string& __p_starttime, const ::std::string& __p_endtime, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_queryData(__p_ident, __p_DataType, __p_InstrumentID, __p_starttime, __p_endtime, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_queryData(const ::Ice::Identity& __p_ident, const ::std::string& __p_DataType, const ::std::string& __p_InstrumentID, const ::std::string& __p_starttime, const ::std::string& __p_endtime, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_queryData(__p_ident, __p_DataType, __p_InstrumentID, __p_starttime, __p_endtime, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_queryData(const ::Ice::Identity& __p_ident, const ::std::string& __p_DataType, const ::std::string& __p_InstrumentID, const ::std::string& __p_starttime, const ::std::string& __p_endtime, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_queryData(const ::Ice::Identity& __p_ident, const ::std::string& __p_DataType, const ::std::string& __p_InstrumentID, const ::std::string& __p_starttime, const ::std::string& __p_endtime)
    {
        return begin_queryData(__p_ident, __p_DataType, __p_InstrumentID, __p_starttime, __p_endtime, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_queryData(const ::Ice::Identity& __p_ident, const ::std::string& __p_DataType, const ::std::string& __p_InstrumentID, const ::std::string& __p_starttime, const ::std::string& __p_endtime, const ::Ice::Context& __ctx)
    {
        return begin_queryData(__p_ident, __p_DataType, __p_InstrumentID, __p_starttime, __p_endtime, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_queryData(const ::Ice::Identity& __p_ident, const ::std::string& __p_DataType, const ::std::string& __p_InstrumentID, const ::std::string& __p_starttime, const ::std::string& __p_endtime, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_queryData(__p_ident, __p_DataType, __p_InstrumentID, __p_starttime, __p_endtime, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_queryData(const ::Ice::Identity& __p_ident, const ::std::string& __p_DataType, const ::std::string& __p_InstrumentID, const ::std::string& __p_starttime, const ::std::string& __p_endtime, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_queryData(__p_ident, __p_DataType, __p_InstrumentID, __p_starttime, __p_endtime, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_queryData(const ::Ice::Identity& __p_ident, const ::std::string& __p_DataType, const ::std::string& __p_InstrumentID, const ::std::string& __p_starttime, const ::std::string& __p_endtime, const ::MdPast::Callback_MdSession_queryDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_queryData(__p_ident, __p_DataType, __p_InstrumentID, __p_starttime, __p_endtime, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_queryData(const ::Ice::Identity& __p_ident, const ::std::string& __p_DataType, const ::std::string& __p_InstrumentID, const ::std::string& __p_starttime, const ::std::string& __p_endtime, const ::Ice::Context& __ctx, const ::MdPast::Callback_MdSession_queryDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_queryData(__p_ident, __p_DataType, __p_InstrumentID, __p_starttime, __p_endtime, &__ctx, __del, __cookie);
    }

    ::std::string end_queryData(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string queryData(const ::Ice::Identity&, const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_queryData(const ::Ice::Identity&, const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::std::string queryInstruments(const ::MdPast::StringList& __p_symbols, const ::MdPast::StringList& __p_products, const ::MdPast::StringList& __p_exchanges, const ::MdPast::IntList& __p_rank, const ::MdPast::StringList& __p_productclass, const ::MdPast::IntList& __p_istrading)
    {
        return queryInstruments(__p_symbols, __p_products, __p_exchanges, __p_rank, __p_productclass, __p_istrading, 0);
    }
    ::std::string queryInstruments(const ::MdPast::StringList& __p_symbols, const ::MdPast::StringList& __p_products, const ::MdPast::StringList& __p_exchanges, const ::MdPast::IntList& __p_rank, const ::MdPast::StringList& __p_productclass, const ::MdPast::IntList& __p_istrading, const ::Ice::Context& __ctx)
    {
        return queryInstruments(__p_symbols, __p_products, __p_exchanges, __p_rank, __p_productclass, __p_istrading, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_queryInstruments(const ::MdPast::StringList& __p_symbols, const ::MdPast::StringList& __p_products, const ::MdPast::StringList& __p_exchanges, const ::MdPast::IntList& __p_rank, const ::MdPast::StringList& __p_productclass, const ::MdPast::IntList& __p_istrading, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_queryInstruments(__p_symbols, __p_products, __p_exchanges, __p_rank, __p_productclass, __p_istrading, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_queryInstruments(const ::MdPast::StringList& __p_symbols, const ::MdPast::StringList& __p_products, const ::MdPast::StringList& __p_exchanges, const ::MdPast::IntList& __p_rank, const ::MdPast::StringList& __p_productclass, const ::MdPast::IntList& __p_istrading, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_queryInstruments(__p_symbols, __p_products, __p_exchanges, __p_rank, __p_productclass, __p_istrading, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_queryInstruments(const ::MdPast::StringList& __p_symbols, const ::MdPast::StringList& __p_products, const ::MdPast::StringList& __p_exchanges, const ::MdPast::IntList& __p_rank, const ::MdPast::StringList& __p_productclass, const ::MdPast::IntList& __p_istrading, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_queryInstruments(__p_symbols, __p_products, __p_exchanges, __p_rank, __p_productclass, __p_istrading, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_queryInstruments(const ::MdPast::StringList& __p_symbols, const ::MdPast::StringList& __p_products, const ::MdPast::StringList& __p_exchanges, const ::MdPast::IntList& __p_rank, const ::MdPast::StringList& __p_productclass, const ::MdPast::IntList& __p_istrading, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_queryInstruments(__p_symbols, __p_products, __p_exchanges, __p_rank, __p_productclass, __p_istrading, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_queryInstruments(const ::MdPast::StringList& __p_symbols, const ::MdPast::StringList& __p_products, const ::MdPast::StringList& __p_exchanges, const ::MdPast::IntList& __p_rank, const ::MdPast::StringList& __p_productclass, const ::MdPast::IntList& __p_istrading, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_queryInstruments(const ::MdPast::StringList& __p_symbols, const ::MdPast::StringList& __p_products, const ::MdPast::StringList& __p_exchanges, const ::MdPast::IntList& __p_rank, const ::MdPast::StringList& __p_productclass, const ::MdPast::IntList& __p_istrading)
    {
        return begin_queryInstruments(__p_symbols, __p_products, __p_exchanges, __p_rank, __p_productclass, __p_istrading, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_queryInstruments(const ::MdPast::StringList& __p_symbols, const ::MdPast::StringList& __p_products, const ::MdPast::StringList& __p_exchanges, const ::MdPast::IntList& __p_rank, const ::MdPast::StringList& __p_productclass, const ::MdPast::IntList& __p_istrading, const ::Ice::Context& __ctx)
    {
        return begin_queryInstruments(__p_symbols, __p_products, __p_exchanges, __p_rank, __p_productclass, __p_istrading, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_queryInstruments(const ::MdPast::StringList& __p_symbols, const ::MdPast::StringList& __p_products, const ::MdPast::StringList& __p_exchanges, const ::MdPast::IntList& __p_rank, const ::MdPast::StringList& __p_productclass, const ::MdPast::IntList& __p_istrading, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_queryInstruments(__p_symbols, __p_products, __p_exchanges, __p_rank, __p_productclass, __p_istrading, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_queryInstruments(const ::MdPast::StringList& __p_symbols, const ::MdPast::StringList& __p_products, const ::MdPast::StringList& __p_exchanges, const ::MdPast::IntList& __p_rank, const ::MdPast::StringList& __p_productclass, const ::MdPast::IntList& __p_istrading, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_queryInstruments(__p_symbols, __p_products, __p_exchanges, __p_rank, __p_productclass, __p_istrading, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_queryInstruments(const ::MdPast::StringList& __p_symbols, const ::MdPast::StringList& __p_products, const ::MdPast::StringList& __p_exchanges, const ::MdPast::IntList& __p_rank, const ::MdPast::StringList& __p_productclass, const ::MdPast::IntList& __p_istrading, const ::MdPast::Callback_MdSession_queryInstrumentsPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_queryInstruments(__p_symbols, __p_products, __p_exchanges, __p_rank, __p_productclass, __p_istrading, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_queryInstruments(const ::MdPast::StringList& __p_symbols, const ::MdPast::StringList& __p_products, const ::MdPast::StringList& __p_exchanges, const ::MdPast::IntList& __p_rank, const ::MdPast::StringList& __p_productclass, const ::MdPast::IntList& __p_istrading, const ::Ice::Context& __ctx, const ::MdPast::Callback_MdSession_queryInstrumentsPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_queryInstruments(__p_symbols, __p_products, __p_exchanges, __p_rank, __p_productclass, __p_istrading, &__ctx, __del, __cookie);
    }

    ::std::string end_queryInstruments(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string queryInstruments(const ::MdPast::StringList&, const ::MdPast::StringList&, const ::MdPast::StringList&, const ::MdPast::IntList&, const ::MdPast::StringList&, const ::MdPast::IntList&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_queryInstruments(const ::MdPast::StringList&, const ::MdPast::StringList&, const ::MdPast::StringList&, const ::MdPast::IntList&, const ::MdPast::StringList&, const ::MdPast::IntList&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<MdSession> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_secure(bool __secure) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_twoway() const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_oneway() const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_batchOneway() const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_datagram() const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_batchDatagram() const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_compress(bool __compress) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_timeout(int __timeout) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<MdSession> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<MdSession*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace MdPast
{

class MdSessionCallBack : virtual public ::Ice::Object
{
public:

    typedef MdSessionCallBackPrx ProxyType;
    typedef MdSessionCallBackPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::Ice::Int onTick(const ::std::string&, const ::std::string&, const ::CM::Ticker&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___onTick(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int onBar(const ::std::string&, const ::std::string&, const ::CM::Bar&, ::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___onBar(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int onDay(const ::std::string&, const ::std::string&, const ::CM::DayBar&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___onDay(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const MdSessionCallBack& l, const MdSessionCallBack& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const MdSessionCallBack& l, const MdSessionCallBack& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

class MdSession : virtual public ::Ice::Object
{
public:

    typedef MdSessionPrx ProxyType;
    typedef MdSessionPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::std::string queryData(const ::Ice::Identity&, const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___queryData(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::std::string queryInstruments(const ::MdPast::StringList&, const ::MdPast::StringList&, const ::MdPast::StringList&, const ::MdPast::IntList&, const ::MdPast::StringList&, const ::MdPast::IntList&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___queryInstruments(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const MdSession& l, const MdSession& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const MdSession& l, const MdSession& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace MdPast
{

template<class T>
class CallbackNC_MdSessionCallBack_onTick : public Callback_MdSessionCallBack_onTick_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_MdSessionCallBack_onTick(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MdPast::MdSessionCallBackPrx __proxy = ::MdPast::MdSessionCallBackPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_onTick(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_MdSessionCallBack_onTickPtr
newCallback_MdSessionCallBack_onTick(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MdSessionCallBack_onTick<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_MdSessionCallBack_onTickPtr
newCallback_MdSessionCallBack_onTick(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MdSessionCallBack_onTick<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_MdSessionCallBack_onTick : public Callback_MdSessionCallBack_onTick_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_MdSessionCallBack_onTick(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MdPast::MdSessionCallBackPrx __proxy = ::MdPast::MdSessionCallBackPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_onTick(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_MdSessionCallBack_onTickPtr
newCallback_MdSessionCallBack_onTick(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MdSessionCallBack_onTick<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_MdSessionCallBack_onTickPtr
newCallback_MdSessionCallBack_onTick(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MdSessionCallBack_onTick<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_MdSessionCallBack_onBar : public Callback_MdSessionCallBack_onBar_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_MdSessionCallBack_onBar(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MdPast::MdSessionCallBackPrx __proxy = ::MdPast::MdSessionCallBackPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_onBar(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_MdSessionCallBack_onBarPtr
newCallback_MdSessionCallBack_onBar(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MdSessionCallBack_onBar<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_MdSessionCallBack_onBarPtr
newCallback_MdSessionCallBack_onBar(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MdSessionCallBack_onBar<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_MdSessionCallBack_onBar : public Callback_MdSessionCallBack_onBar_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_MdSessionCallBack_onBar(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MdPast::MdSessionCallBackPrx __proxy = ::MdPast::MdSessionCallBackPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_onBar(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_MdSessionCallBack_onBarPtr
newCallback_MdSessionCallBack_onBar(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MdSessionCallBack_onBar<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_MdSessionCallBack_onBarPtr
newCallback_MdSessionCallBack_onBar(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MdSessionCallBack_onBar<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_MdSessionCallBack_onDay : public Callback_MdSessionCallBack_onDay_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_MdSessionCallBack_onDay(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MdPast::MdSessionCallBackPrx __proxy = ::MdPast::MdSessionCallBackPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_onDay(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_MdSessionCallBack_onDayPtr
newCallback_MdSessionCallBack_onDay(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MdSessionCallBack_onDay<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_MdSessionCallBack_onDayPtr
newCallback_MdSessionCallBack_onDay(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MdSessionCallBack_onDay<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_MdSessionCallBack_onDay : public Callback_MdSessionCallBack_onDay_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_MdSessionCallBack_onDay(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MdPast::MdSessionCallBackPrx __proxy = ::MdPast::MdSessionCallBackPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_onDay(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_MdSessionCallBack_onDayPtr
newCallback_MdSessionCallBack_onDay(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MdSessionCallBack_onDay<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_MdSessionCallBack_onDayPtr
newCallback_MdSessionCallBack_onDay(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MdSessionCallBack_onDay<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_MdSession_queryData : public Callback_MdSession_queryData_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_MdSession_queryData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MdPast::MdSessionPrx __proxy = ::MdPast::MdSessionPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_queryData(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_MdSession_queryDataPtr
newCallback_MdSession_queryData(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MdSession_queryData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_MdSession_queryDataPtr
newCallback_MdSession_queryData(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MdSession_queryData<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_MdSession_queryData : public Callback_MdSession_queryData_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_MdSession_queryData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MdPast::MdSessionPrx __proxy = ::MdPast::MdSessionPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_queryData(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_MdSession_queryDataPtr
newCallback_MdSession_queryData(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MdSession_queryData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_MdSession_queryDataPtr
newCallback_MdSession_queryData(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MdSession_queryData<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_MdSession_queryInstruments : public Callback_MdSession_queryInstruments_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_MdSession_queryInstruments(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MdPast::MdSessionPrx __proxy = ::MdPast::MdSessionPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_queryInstruments(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_MdSession_queryInstrumentsPtr
newCallback_MdSession_queryInstruments(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MdSession_queryInstruments<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_MdSession_queryInstrumentsPtr
newCallback_MdSession_queryInstruments(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MdSession_queryInstruments<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_MdSession_queryInstruments : public Callback_MdSession_queryInstruments_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_MdSession_queryInstruments(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MdPast::MdSessionPrx __proxy = ::MdPast::MdSessionPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_queryInstruments(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_MdSession_queryInstrumentsPtr
newCallback_MdSession_queryInstruments(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MdSession_queryInstruments<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_MdSession_queryInstrumentsPtr
newCallback_MdSession_queryInstruments(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MdSession_queryInstruments<T, CT>(instance, cb, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
