TARGET  := SunGardTradeDataProcess


LIBS    +=  -Wl,-Bstatic -L../../   -lsungard.1.7  ${LIB_SUNGARD17}

INCLUDE += -I./ -I../../  -D  __SUNGARD__VERSION__=17

include ../../../../Makefile

include ../../../Makefile.inc
