// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `Common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Common_h__
#define __Common_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 5
#       error Ice patch level mismatch!
#   endif
#endif

namespace CM
{

struct Ticker
{
    ::Ice::Long Timestamp;
    ::Ice::Double Price;
    ::Ice::Int Volume;
    ::Ice::Double Turnover;
    ::Ice::Double OpenInterest;
    ::Ice::Double TotalVolume;
    ::Ice::Double TotalTurnover;
    ::Ice::Double BidPrice1;
    ::Ice::Double AskPrice1;
    ::Ice::Int BidVolume1;
    ::Ice::Int AskVolume1;
};

struct Bar
{
    ::Ice::Long Timestamp;
    ::Ice::Double High;
    ::Ice::Double Low;
    ::Ice::Double Open;
    ::Ice::Double Close;
    ::Ice::Int Volume;
    ::Ice::Double Turnover;
    ::Ice::Double OpenInterest;
};

struct DayBar
{
    ::Ice::Long Timestamp;
    ::Ice::Double High;
    ::Ice::Double Low;
    ::Ice::Double Open;
    ::Ice::Double Close;
    ::Ice::Double Average;
    ::Ice::Int Volume;
    ::Ice::Double Turnover;
    ::Ice::Double Settlement;
    ::Ice::Double OpenInterest;
    ::Ice::Double PreSettlement;
    ::Ice::Double PreClose;
    ::Ice::Double PreoOpenInterest;
    ::Ice::Double Price;
    ::Ice::Double UpperLimit;
    ::Ice::Double LowerLimit;
};

struct DepthMarketData
{
    ::std::string TradingDay;
    ::std::string InstrumentID;
    ::std::string ExchangeID;
    ::std::string ExchangeInstID;
    ::Ice::Double LastPrice;
    ::Ice::Double PreSettlementPrice;
    ::Ice::Double PreClosePrice;
    ::Ice::Double PreOpenInterest;
    ::Ice::Double OpenPrice;
    ::Ice::Double HighestPrice;
    ::Ice::Double LowestPrice;
    ::Ice::Int Volume;
    ::Ice::Double Turnover;
    ::Ice::Double OpenInterest;
    ::Ice::Double ClosePrice;
    ::Ice::Double SettlementPrice;
    ::Ice::Double UpperLimitPrice;
    ::Ice::Double LowerLimitPrice;
    ::std::string UpdateTime;
    ::Ice::Int UpdateMillisec;
    ::Ice::Double BidPrice1;
    ::Ice::Int BidVolume1;
    ::Ice::Double AskPrice1;
    ::Ice::Int AskVolume1;
    ::Ice::Double AveragePrice;
    ::std::string ActionDay;
};

struct Account
{
    ::std::string tradingday;
    ::std::string fundid;
    ::std::string parentid;
    ::Ice::Double capital;
    ::Ice::Double prebalance;
    ::Ice::Double premargin;
    ::std::string requestid;
    ::Ice::Double balance;
    ::Ice::Double available;
    ::Ice::Double margin;
    ::Ice::Double incap;
    ::Ice::Double outcap;
    ::Ice::Double commission;
    ::Ice::Double closeprofit;
    ::Ice::Double positionprofit;
    ::std::string updatedate;
};

struct Position
{
    ::std::string tradingday;
    ::std::string fundid;
    ::std::string requestid;
    ::std::string instrumentid;
    ::std::string direction;
    ::std::string hedgeflag;
    ::Ice::Int preposition;
    ::Ice::Int preholdposition;
    ::Ice::Int todayholdposition;
    ::Ice::Int position;
    ::Ice::Int openvolume;
    ::Ice::Int closevolume;
    ::Ice::Double openamount;
    ::Ice::Double closeamount;
    ::Ice::Double todayopenaverage;
    ::Ice::Double positioncost;
    ::Ice::Double premargin;
    ::Ice::Double margin;
    ::Ice::Double commission;
    ::Ice::Double closeprofit;
    ::Ice::Double positionprofit;
    ::Ice::Double totalprofile;
    ::std::string positiondate;
    ::std::string updatedate;
    ::Ice::Double closeprofitbytrade;
    ::Ice::Double opencost;
};

struct Done
{
    ::std::string tradingday;
    ::std::string fundid;
    ::std::string requestid;
    ::std::string brokerid;
    ::std::string orderid;
    ::std::string tradeid;
    ::std::string exchangeid;
    ::std::string instrumentid;
    ::std::string direction;
    ::std::string offsetflag;
    ::std::string hedgeflag;
    ::Ice::Double price;
    ::Ice::Int volume;
    ::std::string tradedate;
    ::std::string tradetime;
    ::std::string updatedate;
    ::Ice::Int seq;
    ::std::string parentid;
    ::std::string strategyid;
    ::std::string userid;
    ::std::string signalname;
};

struct Order
{
    ::std::string frontid;
    ::std::string sessionid;
    ::std::string privateno;
    ::std::string exchangeid;
    ::std::string orderid;
    ::std::string tradingday;
    ::std::string fundid;
    ::std::string brokerid;
    ::std::string requestid;
    ::std::string instrumentid;
    ::std::string direction;
    ::std::string offsetflag;
    ::std::string hedgeflag;
    ::Ice::Double price;
    ::Ice::Int volume;
    ::std::string orderstatus;
    ::Ice::Int volumetraded;
    ::std::string orderdate;
    ::std::string ordertime;
    ::Ice::Int oerrno;
    ::std::string oerrmsg;
    ::std::string ordertype;
    ::std::string donetype;
    ::std::string pricetype;
    ::std::string canceltime;
    ::Ice::Int seq;
    ::std::string parentid;
    ::std::string strategyid;
    ::std::string userid;
    ::std::string signalname;
};

struct DoOrder
{
    ::std::string fundid;
    ::std::string exchangeid;
    ::std::string brokerid;
    ::std::string instrumentid;
    ::std::string ordertype;
    ::std::string direction;
    ::std::string offsetflag;
    ::std::string hedgeflag;
    ::Ice::Double price;
    ::Ice::Int volume;
    ::std::string donetype;
    ::Ice::Int seq;
    ::std::string parentid;
    ::std::string strategyid;
    ::std::string userid;
    ::std::string signalname;
    ::std::string tradingday;
    ::std::string requestid;
};

typedef ::std::vector< ::CM::Done> DoneList;

typedef ::std::vector< ::CM::Account> AccountList;

typedef ::std::vector< ::CM::Position> PositionList;

typedef ::std::vector< ::CM::Order> OrderList;

}

namespace Ice
{
template<>
struct StreamableTraits< ::CM::Ticker>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 76;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::CM::Ticker, S>
{
    static void write(S* __os, const ::CM::Ticker& v)
    {
        __os->write(v.Timestamp);
        __os->write(v.Price);
        __os->write(v.Volume);
        __os->write(v.Turnover);
        __os->write(v.OpenInterest);
        __os->write(v.TotalVolume);
        __os->write(v.TotalTurnover);
        __os->write(v.BidPrice1);
        __os->write(v.AskPrice1);
        __os->write(v.BidVolume1);
        __os->write(v.AskVolume1);
    }
};

template<class S>
struct StreamReader< ::CM::Ticker, S>
{
    static void read(S* __is, ::CM::Ticker& v)
    {
        __is->read(v.Timestamp);
        __is->read(v.Price);
        __is->read(v.Volume);
        __is->read(v.Turnover);
        __is->read(v.OpenInterest);
        __is->read(v.TotalVolume);
        __is->read(v.TotalTurnover);
        __is->read(v.BidPrice1);
        __is->read(v.AskPrice1);
        __is->read(v.BidVolume1);
        __is->read(v.AskVolume1);
    }
};

template<>
struct StreamableTraits< ::CM::Bar>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 60;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::CM::Bar, S>
{
    static void write(S* __os, const ::CM::Bar& v)
    {
        __os->write(v.Timestamp);
        __os->write(v.High);
        __os->write(v.Low);
        __os->write(v.Open);
        __os->write(v.Close);
        __os->write(v.Volume);
        __os->write(v.Turnover);
        __os->write(v.OpenInterest);
    }
};

template<class S>
struct StreamReader< ::CM::Bar, S>
{
    static void read(S* __is, ::CM::Bar& v)
    {
        __is->read(v.Timestamp);
        __is->read(v.High);
        __is->read(v.Low);
        __is->read(v.Open);
        __is->read(v.Close);
        __is->read(v.Volume);
        __is->read(v.Turnover);
        __is->read(v.OpenInterest);
    }
};

template<>
struct StreamableTraits< ::CM::DayBar>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 124;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::CM::DayBar, S>
{
    static void write(S* __os, const ::CM::DayBar& v)
    {
        __os->write(v.Timestamp);
        __os->write(v.High);
        __os->write(v.Low);
        __os->write(v.Open);
        __os->write(v.Close);
        __os->write(v.Average);
        __os->write(v.Volume);
        __os->write(v.Turnover);
        __os->write(v.Settlement);
        __os->write(v.OpenInterest);
        __os->write(v.PreSettlement);
        __os->write(v.PreClose);
        __os->write(v.PreoOpenInterest);
        __os->write(v.Price);
        __os->write(v.UpperLimit);
        __os->write(v.LowerLimit);
    }
};

template<class S>
struct StreamReader< ::CM::DayBar, S>
{
    static void read(S* __is, ::CM::DayBar& v)
    {
        __is->read(v.Timestamp);
        __is->read(v.High);
        __is->read(v.Low);
        __is->read(v.Open);
        __is->read(v.Close);
        __is->read(v.Average);
        __is->read(v.Volume);
        __is->read(v.Turnover);
        __is->read(v.Settlement);
        __is->read(v.OpenInterest);
        __is->read(v.PreSettlement);
        __is->read(v.PreClose);
        __is->read(v.PreoOpenInterest);
        __is->read(v.Price);
        __is->read(v.UpperLimit);
        __is->read(v.LowerLimit);
    }
};

template<>
struct StreamableTraits< ::CM::DepthMarketData>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 150;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::CM::DepthMarketData, S>
{
    static void write(S* __os, const ::CM::DepthMarketData& v)
    {
        __os->write(v.TradingDay);
        __os->write(v.InstrumentID);
        __os->write(v.ExchangeID);
        __os->write(v.ExchangeInstID);
        __os->write(v.LastPrice);
        __os->write(v.PreSettlementPrice);
        __os->write(v.PreClosePrice);
        __os->write(v.PreOpenInterest);
        __os->write(v.OpenPrice);
        __os->write(v.HighestPrice);
        __os->write(v.LowestPrice);
        __os->write(v.Volume);
        __os->write(v.Turnover);
        __os->write(v.OpenInterest);
        __os->write(v.ClosePrice);
        __os->write(v.SettlementPrice);
        __os->write(v.UpperLimitPrice);
        __os->write(v.LowerLimitPrice);
        __os->write(v.UpdateTime);
        __os->write(v.UpdateMillisec);
        __os->write(v.BidPrice1);
        __os->write(v.BidVolume1);
        __os->write(v.AskPrice1);
        __os->write(v.AskVolume1);
        __os->write(v.AveragePrice);
        __os->write(v.ActionDay);
    }
};

template<class S>
struct StreamReader< ::CM::DepthMarketData, S>
{
    static void read(S* __is, ::CM::DepthMarketData& v)
    {
        __is->read(v.TradingDay);
        __is->read(v.InstrumentID);
        __is->read(v.ExchangeID);
        __is->read(v.ExchangeInstID);
        __is->read(v.LastPrice);
        __is->read(v.PreSettlementPrice);
        __is->read(v.PreClosePrice);
        __is->read(v.PreOpenInterest);
        __is->read(v.OpenPrice);
        __is->read(v.HighestPrice);
        __is->read(v.LowestPrice);
        __is->read(v.Volume);
        __is->read(v.Turnover);
        __is->read(v.OpenInterest);
        __is->read(v.ClosePrice);
        __is->read(v.SettlementPrice);
        __is->read(v.UpperLimitPrice);
        __is->read(v.LowerLimitPrice);
        __is->read(v.UpdateTime);
        __is->read(v.UpdateMillisec);
        __is->read(v.BidPrice1);
        __is->read(v.BidVolume1);
        __is->read(v.AskPrice1);
        __is->read(v.AskVolume1);
        __is->read(v.AveragePrice);
        __is->read(v.ActionDay);
    }
};

template<>
struct StreamableTraits< ::CM::Account>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 93;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::CM::Account, S>
{
    static void write(S* __os, const ::CM::Account& v)
    {
        __os->write(v.tradingday);
        __os->write(v.fundid);
        __os->write(v.parentid);
        __os->write(v.capital);
        __os->write(v.prebalance);
        __os->write(v.premargin);
        __os->write(v.requestid);
        __os->write(v.balance);
        __os->write(v.available);
        __os->write(v.margin);
        __os->write(v.incap);
        __os->write(v.outcap);
        __os->write(v.commission);
        __os->write(v.closeprofit);
        __os->write(v.positionprofit);
        __os->write(v.updatedate);
    }
};

template<class S>
struct StreamReader< ::CM::Account, S>
{
    static void read(S* __is, ::CM::Account& v)
    {
        __is->read(v.tradingday);
        __is->read(v.fundid);
        __is->read(v.parentid);
        __is->read(v.capital);
        __is->read(v.prebalance);
        __is->read(v.premargin);
        __is->read(v.requestid);
        __is->read(v.balance);
        __is->read(v.available);
        __is->read(v.margin);
        __is->read(v.incap);
        __is->read(v.outcap);
        __is->read(v.commission);
        __is->read(v.closeprofit);
        __is->read(v.positionprofit);
        __is->read(v.updatedate);
    }
};

template<>
struct StreamableTraits< ::CM::Position>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 128;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::CM::Position, S>
{
    static void write(S* __os, const ::CM::Position& v)
    {
        __os->write(v.tradingday);
        __os->write(v.fundid);
        __os->write(v.requestid);
        __os->write(v.instrumentid);
        __os->write(v.direction);
        __os->write(v.hedgeflag);
        __os->write(v.preposition);
        __os->write(v.preholdposition);
        __os->write(v.todayholdposition);
        __os->write(v.position);
        __os->write(v.openvolume);
        __os->write(v.closevolume);
        __os->write(v.openamount);
        __os->write(v.closeamount);
        __os->write(v.todayopenaverage);
        __os->write(v.positioncost);
        __os->write(v.premargin);
        __os->write(v.margin);
        __os->write(v.commission);
        __os->write(v.closeprofit);
        __os->write(v.positionprofit);
        __os->write(v.totalprofile);
        __os->write(v.positiondate);
        __os->write(v.updatedate);
        __os->write(v.closeprofitbytrade);
        __os->write(v.opencost);
    }
};

template<class S>
struct StreamReader< ::CM::Position, S>
{
    static void read(S* __is, ::CM::Position& v)
    {
        __is->read(v.tradingday);
        __is->read(v.fundid);
        __is->read(v.requestid);
        __is->read(v.instrumentid);
        __is->read(v.direction);
        __is->read(v.hedgeflag);
        __is->read(v.preposition);
        __is->read(v.preholdposition);
        __is->read(v.todayholdposition);
        __is->read(v.position);
        __is->read(v.openvolume);
        __is->read(v.closevolume);
        __is->read(v.openamount);
        __is->read(v.closeamount);
        __is->read(v.todayopenaverage);
        __is->read(v.positioncost);
        __is->read(v.premargin);
        __is->read(v.margin);
        __is->read(v.commission);
        __is->read(v.closeprofit);
        __is->read(v.positionprofit);
        __is->read(v.totalprofile);
        __is->read(v.positiondate);
        __is->read(v.updatedate);
        __is->read(v.closeprofitbytrade);
        __is->read(v.opencost);
    }
};

template<>
struct StreamableTraits< ::CM::Done>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 34;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::CM::Done, S>
{
    static void write(S* __os, const ::CM::Done& v)
    {
        __os->write(v.tradingday);
        __os->write(v.fundid);
        __os->write(v.requestid);
        __os->write(v.brokerid);
        __os->write(v.orderid);
        __os->write(v.tradeid);
        __os->write(v.exchangeid);
        __os->write(v.instrumentid);
        __os->write(v.direction);
        __os->write(v.offsetflag);
        __os->write(v.hedgeflag);
        __os->write(v.price);
        __os->write(v.volume);
        __os->write(v.tradedate);
        __os->write(v.tradetime);
        __os->write(v.updatedate);
        __os->write(v.seq);
        __os->write(v.parentid);
        __os->write(v.strategyid);
        __os->write(v.userid);
        __os->write(v.signalname);
    }
};

template<class S>
struct StreamReader< ::CM::Done, S>
{
    static void read(S* __is, ::CM::Done& v)
    {
        __is->read(v.tradingday);
        __is->read(v.fundid);
        __is->read(v.requestid);
        __is->read(v.brokerid);
        __is->read(v.orderid);
        __is->read(v.tradeid);
        __is->read(v.exchangeid);
        __is->read(v.instrumentid);
        __is->read(v.direction);
        __is->read(v.offsetflag);
        __is->read(v.hedgeflag);
        __is->read(v.price);
        __is->read(v.volume);
        __is->read(v.tradedate);
        __is->read(v.tradetime);
        __is->read(v.updatedate);
        __is->read(v.seq);
        __is->read(v.parentid);
        __is->read(v.strategyid);
        __is->read(v.userid);
        __is->read(v.signalname);
    }
};

template<>
struct StreamableTraits< ::CM::Order>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 49;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::CM::Order, S>
{
    static void write(S* __os, const ::CM::Order& v)
    {
        __os->write(v.frontid);
        __os->write(v.sessionid);
        __os->write(v.privateno);
        __os->write(v.exchangeid);
        __os->write(v.orderid);
        __os->write(v.tradingday);
        __os->write(v.fundid);
        __os->write(v.brokerid);
        __os->write(v.requestid);
        __os->write(v.instrumentid);
        __os->write(v.direction);
        __os->write(v.offsetflag);
        __os->write(v.hedgeflag);
        __os->write(v.price);
        __os->write(v.volume);
        __os->write(v.orderstatus);
        __os->write(v.volumetraded);
        __os->write(v.orderdate);
        __os->write(v.ordertime);
        __os->write(v.oerrno);
        __os->write(v.oerrmsg);
        __os->write(v.ordertype);
        __os->write(v.donetype);
        __os->write(v.pricetype);
        __os->write(v.canceltime);
        __os->write(v.seq);
        __os->write(v.parentid);
        __os->write(v.strategyid);
        __os->write(v.userid);
        __os->write(v.signalname);
    }
};

template<class S>
struct StreamReader< ::CM::Order, S>
{
    static void read(S* __is, ::CM::Order& v)
    {
        __is->read(v.frontid);
        __is->read(v.sessionid);
        __is->read(v.privateno);
        __is->read(v.exchangeid);
        __is->read(v.orderid);
        __is->read(v.tradingday);
        __is->read(v.fundid);
        __is->read(v.brokerid);
        __is->read(v.requestid);
        __is->read(v.instrumentid);
        __is->read(v.direction);
        __is->read(v.offsetflag);
        __is->read(v.hedgeflag);
        __is->read(v.price);
        __is->read(v.volume);
        __is->read(v.orderstatus);
        __is->read(v.volumetraded);
        __is->read(v.orderdate);
        __is->read(v.ordertime);
        __is->read(v.oerrno);
        __is->read(v.oerrmsg);
        __is->read(v.ordertype);
        __is->read(v.donetype);
        __is->read(v.pricetype);
        __is->read(v.canceltime);
        __is->read(v.seq);
        __is->read(v.parentid);
        __is->read(v.strategyid);
        __is->read(v.userid);
        __is->read(v.signalname);
    }
};

template<>
struct StreamableTraits< ::CM::DoOrder>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 31;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::CM::DoOrder, S>
{
    static void write(S* __os, const ::CM::DoOrder& v)
    {
        __os->write(v.fundid);
        __os->write(v.exchangeid);
        __os->write(v.brokerid);
        __os->write(v.instrumentid);
        __os->write(v.ordertype);
        __os->write(v.direction);
        __os->write(v.offsetflag);
        __os->write(v.hedgeflag);
        __os->write(v.price);
        __os->write(v.volume);
        __os->write(v.donetype);
        __os->write(v.seq);
        __os->write(v.parentid);
        __os->write(v.strategyid);
        __os->write(v.userid);
        __os->write(v.signalname);
        __os->write(v.tradingday);
        __os->write(v.requestid);
    }
};

template<class S>
struct StreamReader< ::CM::DoOrder, S>
{
    static void read(S* __is, ::CM::DoOrder& v)
    {
        __is->read(v.fundid);
        __is->read(v.exchangeid);
        __is->read(v.brokerid);
        __is->read(v.instrumentid);
        __is->read(v.ordertype);
        __is->read(v.direction);
        __is->read(v.offsetflag);
        __is->read(v.hedgeflag);
        __is->read(v.price);
        __is->read(v.volume);
        __is->read(v.donetype);
        __is->read(v.seq);
        __is->read(v.parentid);
        __is->read(v.strategyid);
        __is->read(v.userid);
        __is->read(v.signalname);
        __is->read(v.tradingday);
        __is->read(v.requestid);
    }
};

}

#include <IceUtil/PopDisableWarnings.h>
#endif
